### ISSUE TITLE
Call React methods from Vue

### ISSUE THREAD

**Issue by juanparati** [nmpribeiro/vuera-ts#3]
I used vuera-ts integrating some React components into Vue and it works great passing properties and listening events however how can I call methods that uses "useRef" from Vue?

In Vue normally we call methods from a child component with something like `this.$ref.childComp.mymethod()`.

**Comment by juanparati** [comment]
@nmpribeiro : I found that is not possible to call the methods without the internal reference to the React Component, so I improved vuera-ts with a proxy method that will provide the internal reference.

See: https://github.com/nmpribeiro/vuera-ts/pull/4

**Comment by tachyon-ops** [comment]
@juanparati thanks for contributing. I will have a look at the PR :)

**Comment by nmpribeiro** [comment]
`$refs.myReactComp.reactRef().reactMethodFooBar()` does the IDE figure  the `reactMethodFooBar` type - so does the typing works with autocompletion?

**Comment by tachyon-ops** [comment]
@juanparati should be ready to use with version [1.0.7](https://www.npmjs.com/package/vuera-ts). Thanks for your contribution!
